language: python
python:
  - "2.7"

install:

  
    - python setup.py install

script:

    # command to run tests
    - python -m unittest python_webserver_installer.tests.test_python_webserver_installer
